// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_tactical_nuke_incoming = "CgkIi7TOuvMXEAIQAg"; // <GPGSID>
        public const string achievement_lol_nerd = "CgkIi7TOuvMXEAIQBQ"; // <GPGSID>
        public const string achievement_and_i_would_walk_500_more = "CgkIi7TOuvMXEAIQBA"; // <GPGSID>
        public const string leaderboard_leaderboards = "CgkIi7TOuvMXEAIQBg"; // <GPGSID>
        public const string achievement_i_would_walk_500_miles = "CgkIi7TOuvMXEAIQAw"; // <GPGSID>
        public const string achievement_better_safe_than_sorry = "CgkIi7TOuvMXEAIQCQ"; // <GPGSID>
        public const string achievement_200_iq = "CgkIi7TOuvMXEAIQCg"; // <GPGSID>
        public const string achievement_winner_mentality = "CgkIi7TOuvMXEAIQCw"; // <GPGSID>
        public const string achievement_hit_or_miss = "CgkIi7TOuvMXEAIQAQ"; // <GPGSID>

}

